package com.lunarcodes.fetch;

import org.apache.log4j.Logger;

/**
 * Arun.. this class was generated by Maven. Just dont want to delete it. 
 * Hello world! 
 *
 */
public class App 
{
	protected final static Logger LOG = Logger.getLogger(App.class);
	
    public static void main( String[] args )
    {
    	//Log4j check
        LOG.debug( "Hello World!" );
    }
}
